// Copyright 2026 FeatBit
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"
	"testing"
)

var (
	markdownLinkPattern         = regexp.MustCompile(`\[[^\]]*\]\(([^)]+)\)`)
	htmlLinkPattern             = regexp.MustCompile(`href="([^"]+)"`)
	uuidValuePattern            = regexp.MustCompile(`(?i)\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b`)
	publicGuidanceMarkdownFiles = []string{
		"SECURITY.md",
		"SUPPORT.md",
		"UPGRADING.md",
	}
)

func TestRegistryDocumentationMatchesFrozenSurface(t *testing.T) {
	t.Parallel()

	snapshot := readDocumentationReleaseSnapshot(t)
	assertRegistryPages(t, "resources", snapshot.Resources)
	assertRegistryPages(t, "data-sources", snapshot.DataSources)

	index := normalizedDocumentationText(readDocumentationFile(t, "docs/index.md"))
	for _, expected := range []string{
		"FEATBIT_ACCESS_TOKEN",
		"## API endpoint",
		`api_url = "https://featbit.example.com/api/v1"`,
		"leave `api_url` unset and export the same URL through `FEATBIT_API_URL`",
		"either no path or `/api/v1`",
		"documented `/api/v1` origin",
		"configurable origin does not certify",
		"<project_uuid>",
		"<project_uuid>/<environment_uuid>",
		"<environment_uuid>/<exact_key>",
		"<environment_uuid>/<segment_uuid>",
		"<!-- schema generated by tfplugindocs -->",
	} {
		if !strings.Contains(index, expected) {
			t.Errorf("docs/index.md does not contain %q", expected)
		}
	}

	featureFlag := readDocumentationFile(t, "docs/resources/feature_flag.md")
	featureFlagText := normalizedDocumentationText(featureFlag)
	for _, expected := range []string{
		"Only `name` updates in place",
		"Targeting, rules, percentage rollouts, enabled state, and tags remain owned",
		"archives the flag, permanently deletes it",
	} {
		if !strings.Contains(featureFlagText, expected) {
			t.Errorf("Feature Flag documentation does not contain %q", expected)
		}
	}

	segmentResource := readDocumentationFile(t, "docs/resources/segment.md")
	segmentResourceText := normalizedDocumentationText(segmentResource)
	for _, expected := range []string{
		"only an `environment-specific` Segment",
		"Shared Segments are deliberately read-only",
		"checks exact Feature Flag references",
		"archives, permanently deletes",
	} {
		if !strings.Contains(segmentResourceText, expected) {
			t.Errorf("Segment resource documentation does not contain %q", expected)
		}
	}
	segmentDataSource := readDocumentationFile(t, "docs/data-sources/segment.md")
	if !strings.Contains(normalizedDocumentationText(segmentDataSource),
		"both `environment-specific` and `shared` Segments") {
		t.Error("Segment data source documentation does not state its shared read-only contract")
	}
}

func TestRegistryExamplesAreCredentialFreeAndComplete(t *testing.T) {
	t.Parallel()

	snapshot := readDocumentationReleaseSnapshot(t)
	providerExample := readDocumentationFile(t, "examples/provider/provider.tf")
	for _, expected := range []string{
		`required_version = ">= 1.0.0"`,
		`source  = "featbit/featbit"`,
		`version = "~> 0.1.0"`,
		`provider "featbit" {`,
		`# api_url = "https://featbit.example.com/api/v1"`,
		`set FEATBIT_API_URL to the same form`,
	} {
		if !strings.Contains(providerExample, expected) {
			t.Errorf("provider example does not contain %q", expected)
		}
	}

	for typeName := range snapshot.Resources {
		directory := filepath.Join("examples", "resources", typeName)
		assertDocumentationPathExists(t, filepath.Join(directory, "resource.tf"))
		importPath := filepath.Join(directory, "import.sh")
		actual := readDocumentationFile(t, importPath)
		want := fmt.Sprintf("terraform import %s.example '%s'\n", typeName, releaseImportForms[typeName])
		if actual != want {
			t.Errorf("%s = %q, want %q", importPath, actual, want)
		}
	}
	for typeName := range snapshot.DataSources {
		assertDocumentationPathExists(t,
			filepath.Join("examples", "data-sources", typeName, "data-source.tf"))
	}

	files := publicDocumentationFiles(t)
	for _, path := range files {
		contents := readDocumentationFile(t, path)
		lower := strings.ToLower(contents)
		for _, forbidden := range []string{
			"dev_overrides",
			"filesystem_mirror",
			"tf_cli_config_file",
			"tf_reattach_providers",
			"terraform.tfstate",
			".tfplan",
		} {
			if strings.Contains(lower, forbidden) {
				t.Errorf("%s contains forbidden public documentation marker %q", path, forbidden)
			}
		}
		if strings.HasSuffix(path, ".tf") && regexp.MustCompile(`(?m)^\s*access_token\s*=`).MatchString(contents) {
			t.Errorf("%s assigns access_token instead of using the process environment", path)
		}
		if uuidValuePattern.MatchString(contents) {
			t.Errorf("%s contains a UUID-shaped runtime value", path)
		}
		if regexp.MustCompile(`(?i)[A-Z]:\\|/home/|/Users/`).MatchString(contents) {
			t.Errorf("%s contains an absolute workstation path", path)
		}
	}

	environmentExample := readDocumentationFile(t, "examples/resources/featbit_environment/resource.tf")
	featureFlagExample := readDocumentationFile(t, "examples/resources/featbit_feature_flag/resource.tf")
	segmentExample := readDocumentationFile(t, "examples/resources/featbit_segment/resource.tf")
	for path, check := range map[string]struct {
		contents string
		want     string
	}{
		"Environment":  {environmentExample, "project_id  = featbit_project.example.id"},
		"Feature Flag": {featureFlagExample, "environment_id = featbit_environment.example.id"},
		"Segment":      {segmentExample, "environment_id = featbit_environment.example.id"},
	} {
		if !strings.Contains(check.contents, check.want) {
			t.Errorf("%s example does not encode dependency ordering with %q", path, check.want)
		}
	}
}

func TestPublicDocumentationLinksResolve(t *testing.T) {
	t.Parallel()

	paths := append([]string{"README.md"}, publicGuidanceMarkdownFiles...)
	paths = append(paths, registryMarkdownFiles(t)...)
	for _, path := range paths {
		contents := readDocumentationFile(t, path)
		targets := linkTargets(contents)
		for _, target := range targets {
			if strings.HasPrefix(target, "http://") || strings.HasPrefix(target, "https://") ||
				strings.HasPrefix(target, "mailto:") {
				continue
			}
			pathPart, fragment, _ := strings.Cut(target, "#")
			resolved := path
			if pathPart != "" {
				resolved = filepath.Clean(filepath.Join(filepath.Dir(path), filepath.FromSlash(pathPart)))
				assertDocumentationPathExists(t, resolved)
			}
			if fragment != "" && !markdownHasAnchor(readDocumentationFile(t, resolved), fragment) {
				t.Errorf("%s links to missing anchor %q in %s", path, fragment, resolved)
			}
		}
	}
}

func TestPublicGuidanceIsSafeAndActionable(t *testing.T) {
	t.Parallel()

	checks := []struct {
		path string
		want []string
	}{
		{
			path: "SECURITY.md",
			want: []string{
				"Latest published release",
				"GitHub private vulnerability reporting is not currently enabled",
				"Private security contact requested",
				"The body must contain only that request",
				"FEATBIT_ACCESS_TOKEN",
				"Terraform state or plan",
				"does not promise a response or remediation SLA",
			},
		},
		{
			path: "SUPPORT.md",
			want: []string{
				"SECURITY.md",
				"provider issue",
				"FeatBit account, token issuance, billing",
				"minimal HCL using synthetic names",
				"no response or resolution SLA is promised",
			},
		},
		{
			path: "UPGRADING.md",
			want: []string{
				"patch releases in a published minor line",
				`version = "~> 0.1.0"`,
				"terraform init -upgrade",
				"terraform plan",
				"Do not downgrade blindly",
				"Never edit state JSON by hand",
				"<environment_uuid>/<exact_key>",
			},
		},
	}

	var combined strings.Builder
	for _, check := range checks {
		contents := normalizedDocumentationText(readDocumentationFile(t, check.path))
		combined.WriteString(contents)
		for _, want := range check.want {
			if !strings.Contains(contents, want) {
				t.Errorf("%s does not contain %q", check.path, want)
			}
		}
	}

	readme := readDocumentationFile(t, "README.md")
	for _, target := range publicGuidanceMarkdownFiles {
		if !strings.Contains(readme, "]("+target+")") &&
			!strings.Contains(readme, `href="`+target+`"`) {
			t.Errorf("README.md does not link to %s", target)
		}
	}
	if !strings.Contains(readme, `version = "~> 0.1.0"`) {
		t.Error("README.md does not pin the compatible initial minor line")
	}

	issueTemplate := readDocumentationFile(t, ".github/ISSUE_TEMPLATE/bug_report.yml")
	for _, want := range []string{
		"Do not include access tokens",
		"state or plan content",
		"real runtime identifiers",
		"vulnerability details",
		"minimal credential-free reproduction",
		"I read SUPPORT.md",
		"stop and follow SECURITY.md",
	} {
		if !strings.Contains(issueTemplate, want) {
			t.Errorf("bug report template does not contain %q", want)
		}
	}
	issueConfig := readDocumentationFile(t, ".github/ISSUE_TEMPLATE/config.yml")
	if !strings.Contains(issueConfig, "blank_issues_enabled: true") {
		t.Error("issue template configuration does not retain a blank, detail-free security escalation path")
	}

	combined.WriteString(issueTemplate)
	for _, forbidden := range []string{
		"mailto:",
		"security@",
		"/security/advisories/new",
	} {
		if strings.Contains(strings.ToLower(combined.String()), forbidden) {
			t.Errorf("public guidance contains unverified private reporting route %q", forbidden)
		}
	}
}

func TestDocumentationToolchainIsPinnedAndCheckOnlyByDefault(t *testing.T) {
	t.Parallel()

	docsgen := readDocumentationFile(t, "internal/tools/docsgen/main.go")
	for _, expected := range []string{
		"tfplugindocs@v0.25.0",
		`write := flag.Bool("write", false`,
		`os.MkdirTemp("", "featbit-docs-tool-")`,
		`exec.LookPath("terraform")`,
	} {
		if !strings.Contains(docsgen, expected) {
			t.Errorf("documentation generator does not contain pinned/check-only contract %q", expected)
		}
	}
	makefile := readDocumentationFile(t, "GNUmakefile")
	if !strings.Contains(makefile, "docs:\n\t$(GO) run ./internal/tools/docsgen -write") ||
		!strings.Contains(makefile, "docs-check:\n\t$(GO) run ./internal/tools/docsgen\n\t$(GO) run ./internal/tools/examplecheck") {
		t.Error("GNUmakefile documentation targets do not separate explicit writes from drift checks")
	}
}

func readDocumentationReleaseSnapshot(t *testing.T) releaseContractSnapshot {
	t.Helper()

	contents, err := os.ReadFile(releaseSchemaPath)
	if err != nil {
		t.Fatalf("read release schema: %v", err)
	}
	var snapshot releaseContractSnapshot
	decoder := json.NewDecoder(bytes.NewReader(contents))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&snapshot); err != nil {
		t.Fatalf("decode release schema: %v", err)
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		t.Fatalf("release schema has trailing content: %v", err)
	}
	return snapshot
}

func assertRegistryPages(
	t *testing.T,
	category string,
	schemas map[string]releaseSchemaSnapshot,
) {
	t.Helper()

	want := make([]string, 0, len(schemas))
	for typeName := range schemas {
		shortName := strings.TrimPrefix(typeName, "featbit_")
		want = append(want, shortName+".md")
		assertDocumentationPathExists(t,
			filepath.Join("templates", category, shortName+".md.tmpl"))
	}
	sort.Strings(want)

	entries, err := os.ReadDir(filepath.Join("docs", category))
	if err != nil {
		t.Fatalf("read docs/%s: %v", category, err)
	}
	got := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			t.Fatalf("docs/%s contains unexpected entry %s", category, entry.Name())
		}
		got = append(got, entry.Name())
		contents := readDocumentationFile(t, filepath.Join("docs", category, entry.Name()))
		if !strings.Contains(contents, "<!-- schema generated by tfplugindocs -->") {
			t.Errorf("docs/%s/%s does not contain generated schema", category, entry.Name())
		}
	}
	sort.Strings(got)
	if !slices.Equal(got, want) {
		t.Fatalf("docs/%s pages = %v, want %v", category, got, want)
	}
}

func publicDocumentationFiles(t *testing.T) []string {
	t.Helper()

	paths := append([]string{"README.md"}, publicGuidanceMarkdownFiles...)
	paths = append(paths,
		".github/ISSUE_TEMPLATE/bug_report.yml",
		".github/ISSUE_TEMPLATE/config.yml",
	)
	for _, root := range []string{"docs", "examples", "templates"} {
		err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			paths = append(paths, path)
			return nil
		})
		if err != nil {
			t.Fatalf("walk %s: %v", root, err)
		}
	}
	sort.Strings(paths)
	return paths
}

func registryMarkdownFiles(t *testing.T) []string {
	t.Helper()

	var paths []string
	err := filepath.WalkDir("docs", func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if !entry.IsDir() && filepath.Ext(path) == ".md" {
			paths = append(paths, path)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk Registry documentation: %v", err)
	}
	sort.Strings(paths)
	return paths
}

func linkTargets(contents string) []string {
	var targets []string
	for _, match := range markdownLinkPattern.FindAllStringSubmatch(contents, -1) {
		targets = append(targets, strings.TrimSpace(match[1]))
	}
	for _, match := range htmlLinkPattern.FindAllStringSubmatch(contents, -1) {
		targets = append(targets, strings.TrimSpace(match[1]))
	}
	return targets
}

func markdownHasAnchor(contents string, anchor string) bool {
	anchor = strings.ToLower(anchor)
	if strings.Contains(strings.ToLower(contents), `id="`+anchor+`"`) {
		return true
	}
	for _, line := range strings.Split(contents, "\n") {
		if !strings.HasPrefix(line, "#") {
			continue
		}
		heading := strings.TrimSpace(strings.TrimLeft(line, "#"))
		var slug strings.Builder
		lastHyphen := false
		for _, character := range strings.ToLower(heading) {
			switch {
			case character >= 'a' && character <= 'z', character >= '0' && character <= '9':
				slug.WriteRune(character)
				lastHyphen = false
			case character == ' ', character == '-':
				if slug.Len() != 0 && !lastHyphen {
					slug.WriteByte('-')
					lastHyphen = true
				}
			}
		}
		if strings.TrimSuffix(slug.String(), "-") == anchor {
			return true
		}
	}
	return false
}

func normalizedDocumentationText(contents string) string {
	return strings.Join(strings.Fields(contents), " ")
}

func assertDocumentationPathExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Errorf("documentation path %s does not resolve: %v", path, err)
	}
}

func readDocumentationFile(t *testing.T, path string) string {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(contents)
}
